### ISSUE TITLE
Cell props doesn't implement Fable.React.Props.IProp

### ISSUE THREAD

**Issue by grishace** [fable-compiler/fable-recharts#1]

**Comment by grishace** [comment]
Seems that Fable.Helpers.React.Props Fill & Stroke just works.

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! Yes, as the only important thing here is the name, actually any case with "Fill" or "Stroke" name should work. But anyways I've fixed it here too, thanks again for pointing it out!

**Comment by grishace** [comment]
@alfonsogarciacaro Thanks!
