### ISSUE TITLE
Fable.Recharts

### ISSUE THREAD

**Issue by funkr** [fable-compiler/fable-recharts#16]
Hello!
I try currently to use this module, but it throws strange errors.
This is my example: https://github.com/funkr/Try

The errors are easy to reproduce.

1.  Create a new project with this template SAFE-StackWebAppv2.1.0 (Rider Default Template)
2.  `dotnet add package Fable.Recharts`
3.  `dotnet restore`
4.  Add `open Fable.Recharts` and `barChart [] []` to `index.fs`
5. `dotnet fake build --target run`

Specifically the last errors looks concerning.

ERROR in ./src/Client/Index.fs
Module not found: Error: Can't resolve 'recharts' in 'C:\Projects\fsharp\Try\Berta\src\Client'
 @ ./src/Client/Index.fs 46:0-36 139:187-195
 @ ./src/Client/App.fs
 @ ./src/Client/Client.fsproj
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/Client/index.html] 662 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 530 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
i ｢wdm｣: Failed to compile.
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'

**Comment by alfonsogarciacaro** [comment]
Hmm, never seen that error before. Looks like chokidar (the file watcher used by fable-splitter) and the OS are conflicting for some reason. Would it be possible to try upgrading to Fable 3? Please check latest blog posts in fable.io/blog for instructions

**Comment by funkr** [comment]
I tried it, but even with your fable3-sample App, I end up with this:

Compiled src\App.fs
Fable compilation finished in 723ms
C:/Projects/fsharp/fable3-samples/minimal/src/.fable/Fable.React.7.0.1/Fable.React.Helpers.fs(164,42): (164,72) error FABLE: Cannot resolve Fable.Core.JsInterop.import - Inline call from ../Fable.Recharts.1.1.2/Fable.Recharts.fs(614,4) < ../../App.fs(177,10)

I just checked the repo out; made follwing commands:

1. `dotnet tool install fable --version "3.0.0-nagareyama-*"`
2. `npm install -g parcel-bundler` (Because I havent installed parcel)
3. `dotnet add package Fable.Recharts`
    Added to App.fs: ```fsharp open Fable.Recharts and barChart [] []``` 
4. `dotnet fable watch src --run parcel index.html`

Would you mind to add a Recharts element to your sample app, because I saw, that your sample app uses Feliz which I am totally unaware of. Probably I used it in a totally wrong way. A graph, with asked questions per day, would neatly match in the application, wouldnt it :)

**Comment by funkr** [comment]
I got a little step ahead. I found in the generated `index.fs.js` follwing line:
`import { BarChart, Tooltip, CartesianGrid, Bar, YAxis, XAxis } from "recharts";`

This recharts module was not known. I installed it over Rider and then my application starts with fable3.
So probably there is problem with the generation of BarChart.

**Comment by alfonsogarciacaro** [comment]
Thanks for checking @funkr! I think we fixed that problem but that sample still uses an old beta. Can you please run `dotnet tool update fable --version "3.0.0-nagareyama-*"` and try again?

**Comment by funkr** [comment]
I did the update. This is what I find in the .config:
    "fable": {
      "version": "3.0.0-nagareyama-rc-003",
      "commands": [
        "fable"
      ]
    }

This is what I find in `index.fs.js`


    ...
    import { Props_Margin, Props_Chart } from "./.fable/Fable.Recharts.1.1.2/Fable.Recharts.fs.js";
    import { LineChart, Tooltip, YAxis, XAxis, CartesianGrid } from "recharts";
    import { keyValueList } from "./.fable/fable-library.3.0.0-nagareyama-rc-003/MapUtil.js";
    ...

looks not good! (I tried LineChart)

What also look probably wrong is the regression of the fable compiler version:


    λ dotnet fable watch src/Client --run webpack-dev-server                                                      
    Fable: F# to JS compiler 3.0.0-nagareyama-rc-003                                                              
    Thanks to the contributor! @dbrattli                                                                          
    src\Client> cmd /C "dotnet" restore Client.fsproj                                                             
    Wiederherzustellende Projekte werden ermittelt...                                                           
    Alle Projekte sind für die Wiederherstellung auf dem neuesten Stand.                                        
    Parsing src\Client\Client.fsproj...                                                                           
    Initializing F# compiler...                                                                                   
    Compiling src\Client\Client.fsproj...                                                                         
    F# compilation finished in 6951ms                                                                             
    Skipping Fable compilation of up-to-date JS files                                                             
    Fable compilation finished in 7ms                                                                             
    .> cmd /C "C:\Projects\fsharp\DepotViewer\Albert\node_modules\.bin\webpack-dev-server"                        
    Watching src                                                                                                  
    Bundling for development...                                                                                   
    i ∩╜ówds∩╜ú: Project is running at http://0.0.0.0:8080/                                                       
    i ∩╜ówds∩╜ú: webpack output is served from /                                                                  
    i ∩╜ówds∩╜ú: Content not from webpack is served from C:\Projects\fsharp\DepotViewer\Albert\src\Client\public  
    fable-compiler 2.10.2                                                                                         
    fable: Compiled src\Client\Client.fsproj                                                                      
    fable: Compiled src\Client\App.fs                                                                             
    fable: Compiled .fable\Thoth.Json.5.0.0\Extra.fs                                                              
    fable: Compiled .fable\Fable.Elmish.Debugger.3.2.0\Fable.Import.RemoteDev.fs                                  
    fable: Compiled .fable\Fable.Elmish.HMR.4.0.1\hmr.fs                                                          
    fable: Compiled .fable\Fable.Elmish.3.1.0\cmd.fs                                                              
    fable: Compiled .fable\Fable.Elmish.Debugger.3.2.0\debugger.fs                                                
    fable: Compiled .fable\Fable.Elmish.React.3.0.1\react.fs                                                      
    fable: Compiled .fable\Fable.Elmish.HMR.4.0.1\common.fs                                                       
    fable: Compiled .fable\Fable.Elmish.3.1.0\program.fs                                                          
    fable: Compiled .fable\Thoth.Json.5.0.0\Types.fs                                                              
    fable: Compiled .fable\Thoth.Json.5.0.0\Encode.fs                                                             
    fable: Compiled src\Client\Update.fs                   
    ...

It starts with 3.0 RC3 but then I see this Version number: 2.10.2

**Comment by alfonsogarciacaro** [comment]
The imports look good, the Guide for Recharts shows similar code. What do you find problematic? https://recharts.org/en-US/guide/getting-started

Looking at the logs, it seems Fable 3 starts and when running webpack, Fable 2 is called. Can you please fix the entry in webpack.config.js to point to `index.fs.js` and remove `fable-loader`? You can use this PR as reference: https://github.com/MangelMaxime/fulma-demo/pull/43

**Comment by funkr** [comment]
Ok - then it was a misunderstanding. I thought `dotnet add package Fable.Recharts` does everything. Installing the fs and the js module at once. 

I would have expected an `import { LineChart, BarChart, Tooltip, CartesianGrid, Bar, XAxis, YAxis } from "./.fable/Fable.Recharts.1.1.2/Fable.Recharts.fs.js";`. But I must admit I have actually not experience with Javascript and thought I come along without knowing this stuff using F#/Fable.

I replaced in the `webpack.config.js` the fsharpEntry: './src/Client/Client.fsproj', with this fsharpEntry: './src/Client/App.fs.js'.
`App.fs`is the last F# file in my project. 

The command `dotnet fake build --target run` seems to work, whereas the command ` dotnet fable watch src/Client --run webpack-dev-server
`end up with this error: `[HPM] Error occurred while trying to proxy request /api/IShareholderApi/logonUser from localhost:8080 to http://localhost:8085 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

I don't want you to bother further. You can close the issue.
Thank you!

**Comment by alfonsogarciacaro** [comment]
Thanks @funkr. Ok, let's close the issue as that looks as a Webpack issue (by the error it seems there's an error in the proxy server so Webpack cannot connect).

Yes, `dotnet add package` only works for the .NET packages, the JS ones must be installed with npm/yarn. You can try Femto, a tool that installs both .NET and JS packages for you in compatible projects: https://github.com/Zaid-Ajaj/Femto

Although I'm not sure if Fable.Recharts is compatible yet with Femto. There's another charting library, Feliz.Plotly, which is: https://shmew.github.io/Feliz.Plotly/#/Plotly/Installation

**Comment by alfonsogarciacaro** [comment]
Ah, Feliz.Recharts is also compatible with Femto, we probably only need to add something like this: https://github.com/Zaid-Ajaj/Feliz/blob/ef1ccc7302fe4ad475fcd308b8a2e70b1fffab0a/Feliz.Recharts/Feliz.Recharts.fsproj#L15-L17
