### ISSUE TITLE
How can I dynamically determine chart lines at run time?

### ISSUE THREAD

**Issue by travis-leith** [fable-compiler/fable-recharts#4]
I have the following type

```
type ReadingValue = {
    SensorName:string
    ReadingName:string
    ReadingDate:DateTime
    ReadingValue:float
}
```
and the following test function to generate a chart

```
let lineChartSample (dataOpt:ReadingValue [] option) =
    match dataOpt with
    |Some data ->
        let filteredData = data |> Array.filter (fun r -> r.ReadingName = "Humid")
        lineChart
            [ margin 5. 20. 5. 0.
              Chart.Width 600.
              Chart.Height 300.
              Chart.Data filteredData
              Chart.OnClick onMouseEvent ]
            [ line
                [ Cartesian.Type Monotone
                  Cartesian.DataKey "ReadingValue"
                  P.Stroke "#8884d8"
                  Cartesian.Dot false
                  P.StrokeWidth 2. ]
                []
              xaxis [ Cartesian.DataKey "ReadingDate"] []
              yaxis [] []
        ]
    |_ -> Notification.notification [] [str "No data available"]
```
In general, I don't know the distinct values of `ReadingName` at design time.
But I want to allow the user to select different reading names to add to a single chart. How can I do this given F# is a statically typed language? I would need to dynamically pivot the data so that values associated with each reading name appear in different columns. This wouldn't be too difficult in a dynamic language but F# wants me to define my types in advance.

I see from the [Recharts docs](http://recharts.org/en-US/api/Line#dataKey) that dataKey can take a function. I've been able to find an example of this so I don't know what it does, but could it potentially be useful here?

**Comment by travis-leith** [comment]
Ok, I found how to do it.

The following sort of works

```
let scatterChartTest (dataOpt:ReadingValue [] option) =
    match dataOpt with
    |Some data ->
        let humid, temp = data |> Array.partition (fun r -> r.ReadingName = "Humid")
        scatterChart
            [
                Chart.Width 600.
                Chart.Height 300.
            ]
            [
                xaxis [Cartesian.DataKey "ReadingDateInt"; P.Type "number"; Cartesian.Domain [|"dataMin", "dataMax"|]] []
                yaxis [Cartesian.DataKey "ReadingValue"; P.Type "number"] []
                scatter
                    [
                        Chart.Data temp
                        P.Fill "8884d8"
                    ] []
                scatter
                    [
                        Chart.Data humid
                        P.Fill "82ca9d"
                    ] []
            ]
    |_ -> Notification.notification [] [str "No data available"]
```
The key insight was to notice that I can pass data arrays directly to the children, rather than the parent chart, which means the children can be looking at different data sets.

I will leave this open for now in case someone wants to point out a better way of doing it. I will close it in a couple of days if not, or (to the maintainers) feel free to close it yourself before then.

**Comment by alfonsogarciacaro** [comment]
Hi @ChechyLevas! Sorry for replying so late. I'm not sure to understand the issue here, what's exactly the problem with the static types? Fable allows some tricks to interact with dynamic JS (you can [check the docs](https://fable.io/docs/interacting.html)) and in general you can use `obj` to hold any kind of value at runtime. Does it help?

**Comment by travis-leith** [comment]
Hi @alfonsogarciacaro , the problem was my incorrect understanding of the api. 
I thought that the data could only be supplied at the chart level (with each separate trace/line depending on a different field in the data), as that is how it was done in all the examples I saw. This technique is fine if you can statically define the fields in advance. But if you don't know the fields in advance, then it does not work.
In my second post, I demonstrate a different technique, whereby each trace can be supplied a different data set, which can be used to represent the data more generically in that you no longer need to have separate fields for each trace, but rather a single field occurring in separate data sets for each trace.
