### ISSUE TITLE
How do I translatate this Recharts JS to Recahrts F#/Fable?

### ISSUE THREAD

**Issue by travis-leith** [fable-compiler/fable-recharts#5]
I need to get a scatter chart with no dots. This isn't a vanilla Recharts feature, but there is a hack that can be used to accomplish it.

From #https://github.com/recharts/recharts/issues/1177

```
<Scatter name={model.name} data={model.data} line shape={<RenderNoShape />}   />

//and elsewhere
const RenderNoShape = (props)=>{ 
 return null; 
}
```

**Comment by MangelMaxime** [comment]
```js
//and elsewhere
const RenderNoShape = (props)=>{ 
 return null; 
}
```

can be written as

```fs
let renderNoShape = 
    FunctionComponent.Of(fun (props : obj) ->
        nothing
    )
```

I think (I didn't test the code).

**Comment by travis-leith** [comment]
That works to remove the points, but I am unable to get the lines to show using either of

```f#
                scatter
                    [
                        Chart.Data temp
                        P.Fill "8884d8"
                        Cartesian.Shape renderNoShape
                        Cartesian.Line "true"
                    ] []
                scatter
                    [
                        Chart.Data humid
                        Cartesian.Shape renderNoShape
                        P.Fill "82ca9d"
                        Cartesian.Line true
                    ] []
```
Does that mean this issue is closed, and new one should be created? If so, does that issue belong on this repo, or the Recharts repo?

**Comment by alfonsogarciacaro** [comment]
Ok, I tried this out and after a lot of head scratching I realized the problem in your sample was the hash `#` was missing in the `Fill` prop. [This sample is working in the REPL.](https://fable.io/repl/#?code=LYewJgrgNgpgBAJRgYwBYEMBOAXAzgKHxAAcYA7OAMXQCNYA6JNLPI0i6umRlDHXegAVMJAiXJVaDJOmTZ8oSLDiC4AXklces7EJHEC+bAE9ScACLps6dXADeADwBcASzLYA3HGOv3AX0JYbDgwK3QABgBGWwBtAB87OAc1SPCvYzUAZnC4Py9E5Oz0tQAmcJy8+yS1ABYAVmLUivzqurTvWvLcluSAdnaMyLbuquSm4pLhvziAXXwgkLDwktiE6qKOspGCtTbGgA5m0bVehs2ao53xjqbt6siyxoBOCtnAmGDgLABzNzhgzBwGhwKDqfBwCFwADCfF0AFkfn9EtgSLZPECQNgUcBbDQvJgXN9UMENJgvLAAGYkkG5d4A8hgGCYAByIAAyhgzBpwZDKBAyHIXCAyFCQMBiMLyLoAPIUgAUFP5cDlAEo4ABaAB8cDImNQbm+KrpcFwyCs2CZMJYbPQ4uUah5ENN5stsMdkIhMXdHo9X0wvwoZXocCDIfCwaD3p9EKtOHoAHUXGBsKg4G1w1Ho7HdAAJGCE4lwbIZ6MQualuBeises04GC4FzoMgAcQJYErMw7mZ9DnQDhcuEr3YrUJY9cbZHoABVTPAAERkCDAGhMufD0ujusNpv0SzWADSMGMcDnDjX1Y3Y+3k+ZtvnuGs2AgmBg54vPs3Fuv9AAqmQXMEc7IMAb4Xp2MTlu+xh9gOQ7vh+V4TtOs4nouy6ruuWaITue7oIex5zsYoHwdC2E3neJ4AO75kS2DEfBn7jjuf4ASeADW3z0aW4GQReABeMGDjEpFbkhCBNt88DxE0sxwDxmH-CAIBQNgLjEJWU5KSpan0FCz64CAgJ2HED4iGxMCWLgfCYOgGQnpkRZznEfjyfBsCSWQ7YQV28HOliTIKR6VYkdGgj0LewDzgAgiaaBaVxIXZruYSLNYUSBaWYWUC4UCgnOADE+xFTUYD7AlJGMd+AAybjwNgmAQDAGXRgA9C1IlfkhHLoGYQEiLguDlQxZH0N1Zgvp5TKsmNTUhWWPnvn5FqYM1cFzR6YURfOABCsWoPFq0ekluGpREJSHZCWU5XlhUlGaTxgEN76VUhNVkHVDWzetkJtR1TGTjNJ5gI2oCeU9F4vTugMTYyLLspyX0ha53HGjDTJRcQxCqmCvogPy2DbcYACS7ZAcK1i1Zgc6xS6mDZjadpNfgaOYBjWNqqWQA&html=DwQgJg9gxgLgngBwKYAIAWMC2AbAfAKGAxwKKQEMwCUVgYBLGbJXAMXICNmUBqFAJSRQ05AE4wAzsAD0DJi3w1gmJDHLoYMBAFokARwCu9AG4BeAOQBhCADsYSO9oAqiJOZRRb9uxfsAPGGlibABuDxFRCVVTAxgAM20ADnNqWhU1FBtyFVMAImN6JAB3BAhxXI8vBxg8ovowGDRTMCQCqCRtOoa0ABoUehtGenJsbQkoEaRTAEZc1OBx0XoEGBQJUSg8gH0tgAkAeQBlJx3pbHoOCWlRClgAOgRRCDADWHpbO8wBu4ArCTmZItljB5kCVmsNts9kcTlszhcrjdyLBtJBMA8ni83h8vjZfv9cICoEsVqDicCPE8JBIyvQAOYDCGbXIYLQSABc0mkBhsCAA1nS7p5MNJHhAdPBkBIAALTACsdwAbKKnhLXBJPt8-gDpGCQYpaHrKRBqbSGTYmXlWQgOVyefzBcLrkIIpJZUq7gAmbmYMDSQTCMSSTV47WE3Xk0mEIIUKiEDjPODzMAmfpgPKeOzkAZIUQ6lPGUjSBNgJPR4K4IA&css=EYewJgngBA3gUFKBbAhgJwOYEsB2AuKABgG44BfOAYgGMQcAXFXAUzVgSgFoB3Z4Aayz1OoAB6cAzlgBeuDAVBowrESFGlEnJCGmrxU2TnlRFytHo0m1kmXIUglKsZYAOKMGDtQAjIRfqObiwwegALAgAOQj8AxFDmLAxQ+kjo-0tgFGp+DDQQAFccME5aABsHAkoAMxrSMiA)

Apparently when the fill prop is wrong, there's no error and black is used by default for the points but not for the lines, which was misleading.
